spring:
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate.ddl-auto: create-drop

moviefun:
  datasources:
    movies:
      url: jdbc:mysql://localhost:3306/movies?useSSL=false
      username: root
      password: admin
    albums:
      url: jdbc:mysql://localhost:3306/albums?useSSL=false
      username: root
      password: admin